#!/usr/bin/env python3
"""
monitoring_agent.py

Runs outside Docker. Responsibilities:
- Poll LocalStack CloudWatch logs (filter_log_events) for LOG_GROUP/LOG_STREAM
- Detect log keyword errors/warnings and repeated HTTP status codes (4xx/5xx)
- Read metrics history (metrics/metrics_history.log) and detect anomalies via rolling z-score
- Store alerts in storage/*.json and call remediation_agent(alert)
"""

import os
import json
import time
import re
import math
import threading
from datetime import datetime, timezone, timedelta

import boto3
import numpy as np
import pandas as pd

# -----------------------------
# Configuration (change if needed)
# -----------------------------
LOCALSTACK_ENDPOINT = "http://localhost:4566"   # host -> docker localstack
LOG_GROUP = "flask-log-group"
LOG_STREAM = "flask-stream"

METRICS_HISTORY_FILE = "metrics/metrics_history.log"  # generated by metrics_generator.py
METRICS_SNAPSHOT_FILE = "metrics/metrics.json"

STORAGE_DIR = "storage"
LOGS_COPY = "logs/monitor_logs.log"

LOG_ALERTS_FILE = os.path.join(STORAGE_DIR, "log_alerts.json")
METRIC_ALERTS_FILE = os.path.join(STORAGE_DIR, "metric_alerts.json")

# ensure directories
os.makedirs("metrics", exist_ok=True)
os.makedirs("logs", exist_ok=True)
os.makedirs(STORAGE_DIR, exist_ok=True)

# detection keywords
ERROR_KEYWORDS = [
    "error", "exception", "traceback", "fatal", "critical", "panic", "failed", "failure",
    "oomkilled", "out of memory", "segmentation fault", "segfault"
]
WARNING_KEYWORDS = [
    "warn", "warning", "slow query", "timeout", "retrying", "degraded", "rate exceeded"
]

# HTTP status detection
STATUS_ALERT_THRESHOLD = 5         # number of repeated occurrences to raise alert
STATUS_WINDOW_SECONDS = 60 * 2     # window (seconds) to count repeated occurrences

# rolling z-score params for metric anomaly detection
ROLLING_WINDOW = 5     # history count used (exclude current)
ZSCORE_THRESHOLD = 2.5

# boto3 client for logs (LocalStack endpoint)
logs_client = boto3.client(
    "logs",
    aws_access_key_id="test",
    aws_secret_access_key="test",
    region_name="us-east-1",
    endpoint_url=LOCALSTACK_ENDPOINT
)

# remediation_agent import (user to implement)
try:
    from agents.remediation_agent.remediation_agent import remediation_agent
except Exception:
    # fallback stub
    def remediation_agent(payload):
        print("[remediation_agent stub] called with:", payload)

# -----------------------------
# helpers
# -----------------------------
def now_aws_iso():
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

def append_json_line(path, obj):
    with open(path, "a") as f:
        f.write(json.dumps(obj) + "\n")

def safe_read_json(path):
    try:
        with open(path, "r") as f:
            return json.load(f)
    except Exception:
        return []

def save_alert_list(path, alert):
    # append into a JSON array file (load & append; fallback to newline append on failure)
    try:
        data = []
        if os.path.exists(path):
            data = safe_read_json(path) or []
        data.append(alert)
        with open(path, "w") as f:
            json.dump(data, f, indent=2)
    except Exception:
        append_json_line(path + ".ndjson", alert)

def read_metrics_history_df():
    # read newline-delimited JSON history into DataFrame
    if not os.path.exists(METRICS_HISTORY_FILE):
        return pd.DataFrame()
    rows = []
    with open(METRICS_HISTORY_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                rows.append(obj)
            except Exception:
                continue
    if not rows:
        return pd.DataFrame()
    df = pd.DataFrame(rows)
    if "timestamp" in df.columns:
        df["timestamp"] = pd.to_datetime(df["timestamp"])
    return df.sort_values("timestamp").reset_index(drop=True)

def rolling_zscore(arr, window=ROLLING_WINDOW):
    arr = np.asarray(arr, dtype=float)
    n = len(arr)
    zs = np.full(n, np.nan)
    for i in range(n):
        if i < window:
            continue
        hist = arr[i-window:i]
        mean = np.nanmean(hist)
        std = np.nanstd(hist, ddof=0)
        if np.isfinite(std) and std > 0:
            zs[i] = (arr[i] - mean) / std
    return zs

def contains_status_code(msg):
    # returns status code string if message contains a 3-digit 4xx/5xx code, else None
    m = re.search(r"\b(4\d{2}|5\d{2})\b", msg)
    return m.group(1) if m else None

def is_error_message(msg):
    lower = msg.lower()
    return any(k in lower for k in ERROR_KEYWORDS)

def is_warning_message(msg):
    lower = msg.lower()
    return any(k in lower for k in WARNING_KEYWORDS)

# -----------------------------
# Log monitoring
# -----------------------------
def monitor_logs(poll_interval=1.0):
    print("[monitor_logs] started, polling LocalStack CloudWatch for logGroup:", LOG_GROUP)
    seen_event_ids = set()
    status_events = []  # list of (timestamp, status_code)
    while True:
        try:
            params = {"logGroupName": LOG_GROUP, "logStreamNames": [LOG_STREAM]}
            resp = logs_client.filter_log_events(**params)
            events = resp.get("events", [])
            for ev in events:
                ev_id = ev.get("eventId") or ev.get("ingestionTime") or ev.get("timestamp")
                if ev_id in seen_event_ids:
                    continue
                seen_event_ids.add(ev_id)

                msg = ev.get("message", "") or ""
                ts_ms = ev.get("timestamp")
                if ts_ms:
                    ts_iso = datetime.fromtimestamp(ts_ms / 1000.0, tz=timezone.utc).isoformat()
                    ts_dt = datetime.fromtimestamp(ts_ms / 1000.0, tz=timezone.utc)
                else:
                    ts_iso = now_aws_iso()
                    ts_dt = datetime.now(timezone.utc)

                # append local copy
                with open(LOGS_COPY, "a") as lf:
                    lf.write(f"{ts_iso} {msg}\n")

                # keyword detection
                if is_error_message(msg):
                    alert = {"type": "log_error", "timestamp": ts_iso, "message": msg}
                    print(f"[ALERT] Error occurred: {msg}, timestamp: {ts_iso}")
                    save_alert_list(LOG_ALERTS_FILE, alert)
                    try:
                        remediation_agent(alert)
                    except Exception as e:
                        print("[monitor_logs] remediation_agent failed:", e)

                elif is_warning_message(msg):
                    alert = {"type": "log_warning", "timestamp": ts_iso, "message": msg}
                    print(f"[INFO] Warning detected: {msg}, timestamp: {ts_iso}")
                    save_alert_list(LOG_ALERTS_FILE, alert)

                # status code detection (4xx/5xx)
                sc = contains_status_code(msg)
                if sc:
                    status_events.append((ts_dt, sc))
                    # purge old events beyond window
                    cutoff = datetime.now(timezone.utc) - timedelta(seconds=STATUS_WINDOW_SECONDS)
                    status_events = [(t, s) for (t, s) in status_events if t >= cutoff]

                    # count occurrences of the same status code in window
                    counts = {}
                    for (t, s) in status_events:
                        counts[s] = counts.get(s, 0) + 1

                    if counts.get(sc, 0) >= STATUS_ALERT_THRESHOLD:
                        alert = {
                            "type": "http_status_repeated",
                            "timestamp": ts_iso,
                            "status_code": sc,
                            "count": counts[sc],
                            "sample_message": msg
                        }
                        print(f"[ALERT] Status code {sc} repeated {counts[sc]} times in last {STATUS_WINDOW_SECONDS}s (sample msg: {msg})")
                        save_alert_list(LOG_ALERTS_FILE, alert)
                        try:
                            remediation_agent(alert)
                        except Exception as e:
                            print("[monitor_logs] remediation_agent failed:", e)

            # respect nextToken to avoid reading same events repeatedly
            # LocalStack may or may not return nextToken; we just loop
        except logs_client.exceptions.ResourceNotFoundException:
            # log group/stream not present yet
            # wait and retry
            time.sleep(1)
        except Exception as e:
            print("[monitor_logs] exception:", e)
            time.sleep(1)

        time.sleep(poll_interval)

# -----------------------------
# Metrics monitoring (rolling z-score)
# -----------------------------
def monitor_metrics(poll_interval=1.0, z_threshold=ZSCORE_THRESHOLD, rolling_window=ROLLING_WINDOW):
    print("[monitor_metrics] started, reading", METRICS_HISTORY_FILE)
    while True:
        try:
            df = read_metrics_history_df()
            if df.empty:
                time.sleep(poll_interval)
                continue

            # numeric columns (exclude timestamp)
            numeric_cols = [c for c in df.columns if c != "timestamp"]
            for col in numeric_cols:
                # get series and compute rolling z-scores
                vals = pd.to_numeric(df[col], errors="coerce").fillna(method="ffill").fillna(0).astype(float).values
                zs = rolling_zscore(vals, window=rolling_window)
                if len(zs) == 0:
                    continue
                last_idx = len(zs) - 1
                z_val = zs[last_idx]
                if np.isnan(z_val):
                    continue
                latest_ts = df.loc[last_idx, "timestamp"]
                ts_iso = pd.to_datetime(latest_ts).to_pydatetime().astimezone(timezone.utc).isoformat().replace("+00:00", "Z")
                value = float(df.loc[last_idx, col])

                if abs(z_val) >= z_threshold:
                    alert = {
                        "type": "metric_anomaly",
                        "metric": col,
                        "value": value,
                        "zscore": float(z_val),
                        "timestamp": ts_iso
                    }
                    print(f"[ALERT] Metric anomaly: {col}={value} (z={z_val:.2f}), timestamp: {ts_iso}")
                    save_alert_list(METRIC_ALERTS_FILE, alert)
                    try:
                        remediation_agent(alert)
                    except Exception as e:
                        print("[monitor_metrics] remediation_agent failed:", e)

        except Exception as e:
            print("[monitor_metrics] exception:", e)

        time.sleep(poll_interval)

# -----------------------------
# main
# -----------------------------
if __name__ == "__main__":
    print("[monitoring_agent] starting. LocalStack endpoint:", LOCALSTACK_ENDPOINT)
    t1 = threading.Thread(target=monitor_logs, daemon=True)
    t2 = threading.Thread(target=monitor_metrics, daemon=True)
    t1.start()
    t2.start()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("[monitoring_agent] stopped by user")
