services:
  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,cloudwatch,lambda,logs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
